### ISSUE TITLE
Live merge sometimes fails, "No space left on device" appear in the log

### ISSUE THREAD

**Issue by ahadas** [oVirt/vdsm#352]
Description of problem: sometime snapshot removal fails, leaving VM with disk(s) in illegal state; subsequent tries to remove snapshot fail again

Version-Release number of selected component (if applicable): ovirt-engine-4.5.2.4-1.el8.noarch, oVirt Node 4.5.2 (vdsm-4.50.2.2-1.el8)

How reproducible: not always; issue happens now and then when backup system (storware vprotect, interacting with oVirt via API) tries to delete snapshots

Actual results: snapshot removals fail, and subsequent tries fail again 

Expected results: snapshot is correctly removed

Additional info: issue doesn't happen every time, VMs are always (almost) the same (5 or 6 out of about 40), with no apparent pattern (VM either linux or windows, big or small disks, all hypervisors, ...)

Original bug: https://bugzilla.redhat.com/2122525

Tasks:
- [x] Add bitmaps.prune_bitmaps() (#354)
- [x] Prune bitmaps before cold merge (#354)
- [ ] Prune bitmaps before live merge (#357)
